<?php

namespace AppBundle\Repository\League;

use AppBundle\Repository\AbstractParticipantRepository;

/**
 * ParticipantRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends AbstractParticipantRepository
{
}
