<?php

namespace Pstryk82\LeagueBundle\Repository;

/**
 * StoredEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoredEventRepository extends \Doctrine\ORM\EntityRepository
{
}
